---
Name: omnipay-routes
After: framework/routes#coreroutes
---
Director:
  rules:
    'paymentendpoint/$Identifier/$Status/$ReturnURL' : '\SilverStripe\Omnipay\PaymentGatewayController'
    'dev/payment' : '\SilverStripe\Omnipay\Admin\PaymentDevelopmentAdmin'
